import { Button } from 'antd';
import Link from 'next/link';
import Image from 'next/image';
import hero1 from '/public/hero1.png';
import s12 from '/public/s12.png';
import s13 from '/public/s13.png';
import rArrow from '/public/rArrow.png';
import bat from '/public/bat.png';
import s22 from '/public/s22.png';
import s23 from '/public/s23.png';
import s31 from '/public/s31.png';
import s32 from '/public/s32.png';
import s33 from '/public/s33.png';

export default function Samples() {
    return (
        <div className='flex flex-col items-center'>
            <div className='mb-7 text-black font-bold text-3xl text-center'>
                <span>Characters generated by CooCoo AI</span>
            </div>

            <div className='flex md:flex-row items-center justify-between mb-10 w-5/6 flex-col'>
                <div className='flex flex-col md:items-start items-center'>
                    <span className='text-black text-sm mb-4'>Submarine</span>
                    <Image src={hero1} alt='1' className='w-32'></Image>
                </div>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s12} alt='1' className='w-40'></Image>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s13} alt='1' className='w-52'></Image>
            </div>

            <div className='flex md:flex-row items-center justify-between mb-10 w-5/6 flex-col'>
                <div className='flex flex-col md:items-start items-center'>
                    <span className='text-black text-sm mb-4'>Baby Bat</span>
                    <Image src={bat} alt='1' className='w-32'></Image>
                </div>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s22} alt='1' className='w-40'></Image>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s23} alt='1' className='w-52'></Image>
            </div>

            <div className='flex md:flex-row items-center justify-between mb-10 w-5/6 flex-col'>
                <div className='flex flex-col md:items-start items-center'>
                    <span className='text-black text-sm mb-4'>Baby tiger in a dress with a handbag</span>
                    <Image src={s31} alt='1' className='w-32'></Image>
                </div>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s32} alt='1' className='w-40'></Image>
                <div className='flex justify-center items-center md:rotate-0 rotate-90 box-border h-20 md:h-4'>
                  <Image src={rArrow} alt='' className='w-16 h-4'></Image>
                </div>
                <Image src={s33} alt='1' className='w-52'></Image>
            </div>

            <Link href='/create-character'>
                <Button type='primary' className='mt-7'>
                    Start Creating Characters
                </Button>
            </Link>
        </div>
    );
}
